version: '2.0'

#volumes:

#  django-geopackage-server-media:
#    driver: local

services:

  django-geopackage-server:
    build: .
    image: django-geopackage-server
    ports:
      - 7999:7999
    volumes:
      - ./GPKGServer:/app/GPKGServer

