version: '2.0'

volumes:

  django-geopackage-server_data:
    driver: local
  django-geopackage-server-media:
    driver: local

services:

  django-geopackage-server:
    build: .
    image: django-geopackage-server
    ports:
      - 7999:7999
    volumes:
      - django-geopackage-server_data:/data
      - django-geopackage-server-media:/app/GPKGServer/media

